---

mirror_images:
  case_bundles:
  - name: cert-manager
    inv: Setup
    registries: []
  - name: ocs
    inv: Setup
    registries: 
    - host: registry.redhat.io
      user: "{{ lookup('env', 'REDHAT_IO_USER') }}"
      password: "{{ lookup('env', 'REDHAT_IO_ENTITLEMENT_KEY') }}"
  - name: sbo
    inv: Setup
    registries: []
  catalogs: 
