---
- hosts: localhost
  vars:
    # General configuration
    cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
    cluster_type: quickburn
    username: "{{ lookup('env', 'FYRE_USERNAME') }}"
    password: "{{ lookup('env', 'FYRE_APIKEY') }}"
    ocp_version: "{{ lookup('env', 'OCP_VERSION') }}"
    # Fyre specific configuration
    fyre_cluster_size: "{{ lookup('env', 'FYRE_CLUSTER_SIZE') | default('large', true) }}"
    fyre_product_id: "{{ lookup('env', 'FYRE_PRODUCT_ID') }}"
    # Airgap flag
    airgap_install: "{{ lookup('env', 'AIRGAP_INSTALL') | default(False, true) }}"

    # --- Dev catalog settings ----------------------------------------------------------------------------------------
    # Only required when using the development catalog sources for pre-release installation
    # These are used to set up image pull secret in the openshift-marketplace namespace
    artifactory_username: "{{ lookup('env', 'W3_USERNAME') | lower }}"
    artifactory_apikey: "{{ lookup('env', 'ARTIFACTORY_APIKEY') }}"
    # -----------------------------------------------------------------------------------------------------------------

    # -- Grafana Setup ------------------------------------------------------------------------------------------------
    grafana_user: "{{ lookup('env', 'GRAFANA_USER') }}"
    grafana_password: "{{ lookup('env', 'GRAFANA_PASSWORD') }}"
    grafana_storage_class: "{{ lookup('env', 'GRAFANA_STORAGE_CLASS') | default('rook-ceph-block-internal', True) }}"
    grafana_storage_size: "{{ lookup('env', 'GRAFANA_STORAGE_SIZE') | default('10Gi', True) }}"
    grafana_starting_csv: "{{ lookup('env', 'GRAFANA_STARTING_CSV') | default('grafana-operator.v3.10.3', True) }}"
    grafana_datasource_url: "{{ lookup('env', 'GRAFANA_DATASOURCE_URL') | default('https://thanos-querier.openshift-monitoring.svc:9091', True) }}"
    # -----------------------------------------------------------------------------------------------------------------


    # optionally you can provide information to setup github oauth in the cluster
    # oauth:
    #   github_client_secret_value: "{{ lookup('env', 'OAUTH_CLIENT_SECRET') }}"
    #   github_client_id_value: "{{ lookup('env', 'OAUTH_CLIENT_ID') }}"
    #   github_hostname: github.ibm.com
    #   groups:
    #     - name: group1
    #       users:
    #         - user1
    #         - user2
    #       groups_cluster_rolebindings:
    #         - cluster-admin
    #   organizations:
    #     - org1
    #     - org2
  roles:
    - ibm.mas_devops.ocp_provision
    - ibm.mas_devops.ocp_setup_mas_deps
    - ibm.mas_devops.ocp_setup_ocs
    # - ibm.mas_devops.grafana # TODO - test in Fyre to uncomment this line
