apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: configure-app    
spec:
  params:    
    - name: mas_app_id
      type: string
      default: manage
      description: Maximo Applicaiton Suite Application Id
    - name: mas_instance_id
      type: string
    - default: 'masdev'
      description: Maximo Application Suite Workspace Id
      name: mas_workspace_id
      type: string
      
  stepTemplate:
    env:
      - name: MAS_WORKSPACE_ID
        value: $(params.mas_workspace_id)
      - name: MAS_APP_ID
        value: $(params.mas_app_id)      
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
      - name: LOGDIR
        value: /workspace/logs
    name: ''
    resources: {}
  steps:
    - args:
        - |-
          echo "$(date) Configuring MAS Application"                      
          source /opt/app-root/src/env.sh
          ansible-playbook /opt/app-root/lib/python3.8/site-packages/ansible_collections/ibm/mas_devops/playbooks/mas/configure-app.yml          
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/ibmmas/ansible-devops:latest'
      name: configure-app    
      resources: {}
      workingDir: /workspace/configs
  workspaces:
    - name: configs
