apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: suite-config
spec:
  workspaces:
    - name: configs
  params:
    - name: mas_config_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "/workspace/configs/"
    - name: mas_instance_id
      description: The Instance Id for MAS
      type: string
      default: ""
  stepTemplate:
    env:
      - name: MAS_CONFIG_DIR
        value: $(params.mas_config_dir)
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
      - name: LOGDIR
        value: /workspace/logs
  steps:
    - name: suite-config      
      image: quay.io/ibmmas/ansible-devops:latest
      workingDir: /workspace/configs
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo "$(date) Configuring Suite"                           
          source /opt/app-root/src/env.sh
          ansible-playbook /opt/app-root/src/playbooks/suite-config.yml
