apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-manage
spec:
  workspaces:
  - name: shared-workspace
  params:  
  - name: mas_config_dir
    description: The directory in source that contains yaml manifests
    type: string
    default: "/workspace/configs/"
  - name: mas_instance_id
    description: Maximo Application Suite Instance Id
    type: string
    default: ""
  - name: cpd_entitlement_key
    description: Cloud Pak for Data Entitlement Key
    type: string
    default: ""
  - name: mas_entitlement_key
    description: Maximo Application Suite Entitlement Key
    type: string
    default: ""  
  - name: mas_app_id
    description: Maximo Application Suite Application to Install
    type: string
    default: "manage"  
  - name: mas_workspace_id
    description: Maximo Application Suite Workspace Id
    type: string
    default: "masdev"  
  - default: ''
    description: Maximo Application Suite Entitlement Username
    name: mas_entitlement_username
    type: string
  - default: '8.x'
    description: Maximo Application Suite Entitlement Username
    name: mas_app_channel
    type: string
  - default: 'ibm-operator-catalog'
    description: Maximo Application Suite Entitlement Username
    name: mas_app_catalog_source
    type: string
  - default: cp.icr.io/cp
    name: mas_icr_cp
    type: string
    description: Maximos Application Suite Image registry
  - default: ''
    name: artifactory_apikey
    type: string
    description: Artifactory APIKEY for Development deployment
  - default: ''
    name: artifactory_username
    type: string
    description: Artifactory Username for Development deployment
  tasks:
  - name: install-db2wh
    taskRef:
      name: install-db2wh
      kind: ClusterTask
    workspaces:
    - name: configs
      workspace: shared-workspace
    params:
    - name: mas_config_dir
      value: $(params.mas_config_dir)
    - name: mas_instance_id
      value:  $(params.mas_instance_id)
    - name: cpd_entitlement_key
      value:  $(params.cpd_entitlement_key)
  - name: suite-config
    taskRef:
      name: suite-config
      kind: ClusterTask
    workspaces:
      - name: configs
        workspace: shared-workspace
    params:
    - name: mas_instance_id
      value: $(params.mas_instance_id)
    - name: mas_config_dir
      value: $(params.mas_config_dir)
    runAfter: 
      - install-db2wh
  - name: install-app
    taskRef:
      name: install-app
      kind: ClusterTask
    workspaces:
      - name: configs
        workspace: shared-workspace
    params:
    - name: mas_app_id
      value: $(params.mas_app_id)      
    - name: mas_instance_id
      value: $(params.mas_instance_id)
    - name: mas_entitlement_key
      value: $(params.mas_entitlement_key)
    - name: mas_entitlement_username
      value: $(params.mas_entitlement_username)
    - name: mas_app_channel
      value: $(params.mas_app_channel)
    - name: mas_app_catalog_source
      value: $(params.mas_app_catalog_source)
    - name: artifactory_username
      value: $(params.artifactory_username)
    - name: artifactory_apikey
      value: $(params.artifactory_apikey)
    - name: mas_icr_cp
      value: $(params.mas_icr_cp)
    runAfter: 
      - suite-config
  - name: hack-db2wh-for-manage
    taskRef:
      name: hack-db2wh-for-manage
      kind: ClusterTask
    workspaces:
      - name: configs
        workspace: shared-workspace    
    runAfter: 
      - install-app
  - name: configure-app
    taskRef:
      name: configure-app
      kind: ClusterTask
    workspaces:
      - name: configs
        workspace: shared-workspace
    params:
    - name: mas_app_id
      value: $(params.mas_app_id)      
    - name: mas_instance_id
      value: $(params.mas_instance_id)
    - name: mas_workspace_id
      value: $(params.mas_workspace_id)
    runAfter: 
      - hack-db2wh-for-manage
