---
# 1.  Install Service Binding Operator
# -----------------------------------------------------------------------------
# Important
# Do not upgrade to SBO 0.9.0, there are breaking changes in the API that
# are incompatible with MAS
- name: Deploy SBO
  shell: |
    oc apply -f https://github.com/redhat-developer/service-binding-operator/releases/download/v0.8.0/release.yaml

- name: Wait for SBO install to complete
  community.kubernetes.k8s_info:
    api_version: v1
    name: service-binding-operator
    namespace: service-binding-operator
    kind: Deployment
  register: _sbo_deployment
  until: _sbo_deployment.resources[0].status.availableReplicas is defined
  retries: 10 # Approximately 10 minutes before we give up
  delay: 60 # 1 minute
