apiVersion: db2u.databases.ibm.com/v1
kind: Db2uCluster
metadata:
  name: "{{ db2_instance_id | lower }}"
  namespace: "{{ db2_namespace }}"
spec:
  account:
    privileged: true
    imagePullSecrets:
      - ibm-registry

  addOns:
    graph:
      enabled: false
    rest:
      enabled: false

  version: "{{ db2_version }}"
  size: 1

  environment:
    dbType: db2wh
    database:
      name: "{{ db2_dbname }}"
      settings:
        dftTableOrg: ROW
    instance:
      registry:
        DB2_4K_DEVICE_SUPPORT: "ON"

  license:
    accept: true

  podConfig:
    db2u:
      resource:
        db2u:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 8Gi

  storage:
    - name: meta
      type: "create"
      spec:
        storageClassName: "{{ db2_storage_class }}"
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
    - name: data
      type: "create"
      spec:
        storageClassName: "{{ db2_storage_class }}"
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 100Gi
